version: '3.2'

services:
  app:
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: {{ name }}
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: adev runserver ./{{ name }}/__main__.py
  {% if not without_postgres %}
  postgres:
      image: postgres:10
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432:5432
  {% endif %}
  {% if redis %}
  redis:
    image: redis:4
    ports:
        - 6379:6379
  {% endif %}
